aws_region         = "eu-west-3"
key_name           = "mykeyterraform"
public_key_path    = "mykeyterraform.pub"
private_key_path   = "mykeyterraform.pem"
security_group_name = "app_sg"
ami_id             = "ami-0644165ab979df02d"
instance_type      = "t2.micro"
ssh_user           = "admin"
