- name: Installer les outils de base (curl, git, etc.)
  apt:
    name:
      - curl
      - git
      - build-essential
      - wget
    state: present
    update_cache: yes

- name: Installer Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt install -y nodejs
    npm install -g @angular/cli

- name: Installer MongoDB
  shell: |
    curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
    echo "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" > /etc/apt/sources.list.d/mongodb-org-7.0.list
    apt update
    apt install -y mongodb-org
    systemctl enable mongod --now